### ISSUE TITLE
Address Tomax and Tomin

### ISSUE THREAD

**Issue by AlmeidaAnderson** [dinamitemic/mlx90614#1]
The address for TOmax and TOmin are swapped
![image](https://user-images.githubusercontent.com/37489494/225439572-2be6c629-582a-4b78-85be-80710ad3d9a1.png)

**Comment by dinamitemic** [comment]
[Fix swapped TOMIN and TOMAX defs](https://github.com/dinamitemic/mlx90614/commit/4a95f1bc60074d3588e5dde5f9e682a80c00456e)
